description = 'Main Application Entry Point'

bootJar { enabled = true }
jar { enabled = false }

dependencies {
    implementation project(':common')
    implementation project(':user')
    implementation project(':email')
    implementation project(':rag')
    implementation project(':chatting')
    implementation project(':recruitment')
    implementation project(':matchs')
    implementation project(':review')
    implementation project(':contract')
    implementation project(':settlement')
    implementation project(':subscription')

    implementation 'org.springframework.boot:spring-boot-starter-web'
}