plugins {
    id 'java-library'
}

description = 'payment'

dependencies {
    implementation project(':common')
    implementation project(':contract')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    // Swagger 설정 템플릿 참조용 (필수)
    compileOnly 'org.springdoc:springdoc-openapi-starter-webmvc-ui'
}
